import os
import sys
import time
import signal
import socket
import shutil
import queue
import threading
import subprocess
import webbrowser
from pathlib import Path
import tkinter as tk
from tkinter import messagebox
from tkinter import scrolledtext


# =========================================================
# PM2.5 监控预警平台 科技感可视化启动器
#
# 功能：
# 1. 可视化启动后端 FastAPI
# 2. 可视化启动前端 Vite
# 3. 实时显示前后端运行日志
# 4. 显示服务状态、端口、PID、访问地址
# 5. 一键启动 / 停止 / 重启 / 打开系统
# 6. 支持 PyInstaller 打包为 exe 后作为项目启动器
# =========================================================


BACKEND_PORT = 8000
FRONTEND_PORT = 5173

BACKEND_URL = f"http://127.0.0.1:{BACKEND_PORT}"
FRONTEND_URL = f"http://localhost:{FRONTEND_PORT}"

APP_TITLE = "PM2.5 监控预警平台启动器"


def is_windows() -> bool:
    return os.name == "nt"


def is_frozen() -> bool:
    return getattr(sys, "frozen", False)


def get_app_base_dir() -> Path:
    """
    获取启动器所在目录。

    普通运行：
        使用 start_all.py 所在目录

    打包为 exe：
        使用 exe 所在目录

    注意：
        打包后建议把 exe 放在项目根目录，也就是 backend 和 frontend 的同级目录。
    """

    if is_frozen():
        return Path(sys.executable).resolve().parent

    return Path(__file__).resolve().parent


def find_project_root() -> Path:
    """
    自动寻找项目根目录。

    支持：
    1. start_all.py 放项目根目录
    2. start_all.py 放 scripts 目录
    3. 打包后的 exe 放项目根目录
    """

    start_dir = get_app_base_dir()

    candidates = [start_dir, *start_dir.parents]

    for path in candidates:
        if (path / "backend").exists() and (path / "frontend").exists():
            return path

    raise RuntimeError(
        "未找到项目根目录。\n\n"
        "请确认启动器位于项目目录内，并且项目目录下存在：\n"
        "backend/ 和 frontend/ 两个文件夹。"
    )


PROJECT_ROOT = find_project_root()
BACKEND_DIR = PROJECT_ROOT
FRONTEND_DIR = PROJECT_ROOT / "frontend"

# =========================================================
# 数据库配置
# =========================================================

DB_ENV_PATH = PROJECT_ROOT / ".env"

DB_ENV_KEYS = [
    "DB_HOST",
    "DB_PORT",
    "DB_NAME",
    "DB_USER",
    "DB_PASSWORD",
]

DEFAULT_DB_CONFIG = {
    "DB_HOST": "localhost",
    "DB_PORT": "5432",
    "DB_NAME": "db1",
    "DB_USER": "postgres",
    "DB_PASSWORD": "",
}


def read_env_file(path: Path) -> dict:
    """读取项目根目录 .env 中的数据库配置。"""

    config = dict(DEFAULT_DB_CONFIG)

    if not path.exists():
        return config

    try:
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()

            if not line or line.startswith("#") or "=" not in line:
                continue

            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")

            if key in DB_ENV_KEYS:
                config[key] = value
    except Exception:
        pass

    return config


def write_db_env_file(path: Path, config: dict):
    """把数据库配置写入 .env，同时尽量保留 .env 中的其他配置项。"""

    preserved_lines = []

    if path.exists():
        try:
            for raw_line in path.read_text(encoding="utf-8").splitlines():
                stripped = raw_line.strip()

                if not stripped or stripped.startswith("#") or "=" not in stripped:
                    preserved_lines.append(raw_line)
                    continue

                key = stripped.split("=", 1)[0].strip()

                if key not in DB_ENV_KEYS:
                    preserved_lines.append(raw_line)
        except Exception:
            preserved_lines = []

    db_lines = [
        "",
        "# Database config generated by PM2.5 launcher",
        f"DB_HOST={config.get('DB_HOST', '')}",
        f"DB_PORT={config.get('DB_PORT', '')}",
        f"DB_NAME={config.get('DB_NAME', '')}",
        f"DB_USER={config.get('DB_USER', '')}",
        f"DB_PASSWORD={config.get('DB_PASSWORD', '')}",
    ]

    content = "\n".join(preserved_lines + db_lines).strip() + "\n"
    path.write_text(content, encoding="utf-8")


def is_port_open(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.5)

        try:
            return sock.connect_ex((host, port)) == 0
        except Exception:
            return False


def wait_for_port(host: str, port: int, timeout: int = 30) -> bool:
    start_time = time.time()

    while time.time() - start_time < timeout:
        if is_port_open(host, port):
            return True

        time.sleep(0.4)

    return False


def get_python_command() -> str:
    """
    优先使用项目内 .venv1 的 Python。
    打包成 exe 后，不能用 sys.executable 启动后端，因为 sys.executable 会变成启动器自身。
    """

    venv_python = PROJECT_ROOT / ".venv1" / "Scripts" / "python.exe"

    if venv_python.exists():
        return str(venv_python)

    python_cmd = shutil.which("python")

    if python_cmd:
        return python_cmd

    if not is_frozen():
        return sys.executable

    raise RuntimeError(
        "未找到 Python 解释器。\n\n"
        "建议在项目根目录保留虚拟环境：\n"
        ".venv1\\Scripts\\python.exe\n\n"
        "或者把 Python 加入系统 PATH。"
    )


def get_npm_command() -> str:
    if is_windows():
        npm_cmd = shutil.which("npm.cmd")
    else:
        npm_cmd = shutil.which("npm")

    if not npm_cmd:
        raise RuntimeError(
            "未找到 npm。\n\n"
            "请先安装 Node.js，并确认 npm 已加入系统 PATH。"
        )

    return npm_cmd


def taskkill_pid(pid: int):
    if not is_windows():
        return

    subprocess.run(
        ["taskkill", "/PID", str(pid), "/T", "/F"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )


class ServiceProcess:
    def __init__(self, name, port, url):
        self.name = name
        self.port = port
        self.url = url
        self.process = None
        self.external_running = False

    @property
    def pid(self):
        if self.process and self.process.poll() is None:
            return self.process.pid

        return None

    @property
    def running(self):
        if self.process and self.process.poll() is None:
            return True

        if self.external_running and is_port_open("127.0.0.1", self.port):
            return True

        return False


class TechLauncher:
    def __init__(self, root):
        self.root = root
        self.root.title(APP_TITLE)
        self.root.geometry("1180x840")
        self.root.minsize(1050, 760)
        self.root.configure(bg="#06111f")

        self.log_queue = queue.Queue()

        self.backend = ServiceProcess("后端 FastAPI", BACKEND_PORT, BACKEND_URL)
        self.frontend = ServiceProcess("前端 Vite", FRONTEND_PORT, FRONTEND_URL)

        self.starting = False
        self.stopping = False
        self.auto_open_browser = tk.BooleanVar(value=True)

        self.backend_status_var = tk.StringVar(value="未启动")
        self.frontend_status_var = tk.StringVar(value="未启动")

        self.backend_pid_var = tk.StringVar(value="--")
        self.frontend_pid_var = tk.StringVar(value="--")

        self.backend_port_var = tk.StringVar(value=str(BACKEND_PORT))
        self.frontend_port_var = tk.StringVar(value=str(FRONTEND_PORT))

        self.system_status_var = tk.StringVar(value="待启动")

        db_config = read_env_file(DB_ENV_PATH)
        self.db_host_var = tk.StringVar(value=db_config.get("DB_HOST", "localhost"))
        self.db_port_var = tk.StringVar(value=db_config.get("DB_PORT", "5432"))
        self.db_name_var = tk.StringVar(value=db_config.get("DB_NAME", "db1"))
        self.db_user_var = tk.StringVar(value=db_config.get("DB_USER", "postgres"))
        self.db_password_var = tk.StringVar(value=db_config.get("DB_PASSWORD", ""))
        self.db_status_var = tk.StringVar(value="未验证")

        self._build_ui()
        self._draw_grid()
        self._poll_log_queue()
        self._refresh_status_loop()

        self.root.protocol("WM_DELETE_WINDOW", self.on_close)

    # =====================================================
    # UI 构建
    # =====================================================

    def _build_ui(self):
        self.bg_canvas = tk.Canvas(
            self.root,
            bg="#06111f",
            highlightthickness=0,
        )
        self.bg_canvas.place(x=0, y=0, relwidth=1, relheight=1)

        self.main = tk.Frame(self.root, bg="#06111f")
        self.main.place(x=0, y=0, relwidth=1, relheight=1)

        self._build_header()
        self._build_status_area()
        self._build_database_area()
        self._build_control_area()
        self._build_log_area()
        self._build_footer()

    def _build_header(self):
        header = tk.Frame(self.main, bg="#06111f")
        header.pack(fill="x", padx=28, pady=(22, 10))

        left = tk.Frame(header, bg="#06111f")
        left.pack(side="left", fill="x", expand=True)

        title = tk.Label(
            left,
            text="PM2.5 监控预警平台",
            fg="#36f7ff",
            bg="#06111f",
            font=("Microsoft YaHei UI", 26, "bold"),
        )
        title.pack(anchor="w")

        subtitle = tk.Label(
            left,
            text="FastAPI 后端 · React/Vite 前端 · LSTM PM2.5 预测与预警系统",
            fg="#9eefff",
            bg="#06111f",
            font=("Microsoft YaHei UI", 11),
        )
        subtitle.pack(anchor="w", pady=(6, 0))

        path_label = tk.Label(
            left,
            text=f"项目目录：{PROJECT_ROOT}",
            fg="#6ea8b5",
            bg="#06111f",
            font=("Consolas", 9),
        )
        path_label.pack(anchor="w", pady=(4, 0))

        right = tk.Frame(header, bg="#06111f")
        right.pack(side="right")

        status_box = tk.Frame(
            right,
            bg="#092235",
            highlightbackground="#0ff",
            highlightthickness=1,
        )
        status_box.pack()

        tk.Label(
            status_box,
            text="SYSTEM STATUS",
            fg="#36f7ff",
            bg="#092235",
            font=("Consolas", 10, "bold"),
        ).pack(padx=18, pady=(10, 2))

        tk.Label(
            status_box,
            textvariable=self.system_status_var,
            fg="#ffffff",
            bg="#092235",
            font=("Microsoft YaHei UI", 13, "bold"),
        ).pack(padx=18, pady=(0, 10))

    def _build_status_area(self):
        area = tk.Frame(self.main, bg="#06111f")
        area.pack(fill="x", padx=28, pady=10)

        self.backend_card = self._create_service_card(
            area,
            title="后端服务",
            subtitle="FastAPI · Uvicorn · PostgreSQL · LSTM 模型接口",
            status_var=self.backend_status_var,
            pid_var=self.backend_pid_var,
            port_var=self.backend_port_var,
            url=BACKEND_URL,
            accent="#36f7ff",
        )
        self.backend_card.pack(side="left", fill="x", expand=True, padx=(0, 10))

        self.frontend_card = self._create_service_card(
            area,
            title="前端服务",
            subtitle="React · Vite · 可视化预测页面 · 管理员后台",
            status_var=self.frontend_status_var,
            pid_var=self.frontend_pid_var,
            port_var=self.frontend_port_var,
            url=FRONTEND_URL,
            accent="#7cffb2",
        )
        self.frontend_card.pack(side="left", fill="x", expand=True, padx=(10, 0))

    def _create_service_card(
        self,
        parent,
        title,
        subtitle,
        status_var,
        pid_var,
        port_var,
        url,
        accent,
    ):
        card = tk.Frame(
            parent,
            bg="#0a1b2c",
            highlightbackground="#17394f",
            highlightthickness=1,
        )

        top = tk.Frame(card, bg="#0a1b2c")
        top.pack(fill="x", padx=18, pady=(16, 8))

        dot = tk.Canvas(top, width=14, height=14, bg="#0a1b2c", highlightthickness=0)
        dot.pack(side="left", padx=(0, 8))
        dot.create_oval(2, 2, 12, 12, fill=accent, outline=accent)

        tk.Label(
            top,
            text=title,
            fg=accent,
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 16, "bold"),
        ).pack(side="left")

        tk.Label(
            card,
            text=subtitle,
            fg="#b7d6e3",
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 10),
        ).pack(anchor="w", padx=18)

        info = tk.Frame(card, bg="#0a1b2c")
        info.pack(fill="x", padx=18, pady=14)

        self._info_item(info, "状态", status_var, 0, accent)
        self._info_item(info, "PID", pid_var, 1, accent)
        self._info_item(info, "端口", port_var, 2, accent)

        tk.Label(
            card,
            text=url,
            fg="#d9fbff",
            bg="#092235",
            font=("Consolas", 11, "bold"),
            padx=12,
            pady=8,
        ).pack(fill="x", padx=18, pady=(0, 16))

        return card

    def _info_item(self, parent, label, var, col, accent):
        box = tk.Frame(parent, bg="#092235")
        box.grid(row=0, column=col, sticky="ew", padx=5)

        parent.grid_columnconfigure(col, weight=1)

        tk.Label(
            box,
            text=label,
            fg="#82a9b8",
            bg="#092235",
            font=("Microsoft YaHei UI", 9),
        ).pack(pady=(8, 2))

        tk.Label(
            box,
            textvariable=var,
            fg=accent,
            bg="#092235",
            font=("Consolas", 12, "bold"),
        ).pack(pady=(0, 8))


    def _build_database_area(self):
        area = tk.Frame(
            self.main,
            bg="#0a1b2c",
            highlightbackground="#17394f",
            highlightthickness=1,
        )
        area.pack(fill="x", padx=28, pady=(0, 12))

        header = tk.Frame(area, bg="#0a1b2c")
        header.pack(fill="x", padx=16, pady=(12, 8))

        tk.Label(
            header,
            text="数据库配置",
            fg="#36f7ff",
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 15, "bold"),
        ).pack(side="left")

        tk.Label(
            header,
            text="启动后端前会把以下配置注入环境变量 DB_HOST / DB_PORT / DB_NAME / DB_USER / DB_PASSWORD",
            fg="#7a9cab",
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 9),
        ).pack(side="left", padx=14)

        tk.Label(
            header,
            textvariable=self.db_status_var,
            fg="#ffd166",
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 10, "bold"),
        ).pack(side="right")

        form = tk.Frame(area, bg="#0a1b2c")
        form.pack(fill="x", padx=16, pady=(2, 12))

        self._db_field(form, "主机", self.db_host_var, 0, width=18)
        self._db_field(form, "端口", self.db_port_var, 1, width=8)
        self._db_field(form, "数据库名", self.db_name_var, 2, width=16)
        self._db_field(form, "用户名", self.db_user_var, 3, width=14)
        self._db_field(form, "密码", self.db_password_var, 4, width=16, show="*")

        btn_box = tk.Frame(form, bg="#0a1b2c")
        btn_box.grid(row=0, column=5, sticky="e", padx=(14, 0))

        self.verify_db_btn = self._button(
            btn_box,
            "验证数据库",
            self.verify_database_async,
            bg="#0c4f6f",
            fg="#c8f7ff",
            width=12,
            height=1,
        )
        self.verify_db_btn.pack(side="left", padx=(0, 8))

        self.save_db_btn = self._button(
            btn_box,
            "保存配置",
            self.save_database_config,
            bg="#10283a",
            fg="#9eefff",
            width=10,
            height=1,
        )
        self.save_db_btn.pack(side="left")

        form.grid_columnconfigure(5, weight=1)

    def _db_field(self, parent, label, var, col, width=14, show=None):
        box = tk.Frame(parent, bg="#0a1b2c")
        box.grid(row=0, column=col, sticky="w", padx=(0, 10))

        tk.Label(
            box,
            text=label,
            fg="#82a9b8",
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 9),
        ).pack(anchor="w", pady=(0, 3))

        entry = tk.Entry(
            box,
            textvariable=var,
            width=width,
            show=show,
            bg="#030b12",
            fg="#d9fbff",
            insertbackground="#36f7ff",
            relief="flat",
            font=("Consolas", 10),
        )
        entry.pack(anchor="w", ipady=5)

    def _build_control_area(self):
        area = tk.Frame(self.main, bg="#06111f")
        area.pack(fill="x", padx=28, pady=(4, 14))

        left = tk.Frame(area, bg="#06111f")
        left.pack(side="left", fill="x", expand=True)

        self.start_btn = self._button(
            left,
            "启动全部",
            self.start_all,
            bg="#0884ff",
            fg="#ffffff",
            width=12,
        )
        self.start_btn.pack(side="left", padx=(0, 10))

        self.stop_btn = self._button(
            left,
            "停止全部",
            self.stop_all,
            bg="#802020",
            fg="#ffdede",
            width=12,
        )
        self.stop_btn.pack(side="left", padx=10)

        self.restart_btn = self._button(
            left,
            "重启全部",
            self.restart_all,
            bg="#0c4f6f",
            fg="#c8f7ff",
            width=12,
        )
        self.restart_btn.pack(side="left", padx=10)

        self.open_btn = self._button(
            left,
            "打开系统",
            self.open_frontend,
            bg="#097a47",
            fg="#eafff2",
            width=12,
        )
        self.open_btn.pack(side="left", padx=10)

        self.check_btn = self._button(
            left,
            "环境检查",
            self.check_environment,
            bg="#1b3348",
            fg="#36f7ff",
            width=12,
        )
        self.check_btn.pack(side="left", padx=10)

        right = tk.Frame(area, bg="#06111f")
        right.pack(side="right")

        tk.Checkbutton(
            right,
            text="启动后自动打开浏览器",
            variable=self.auto_open_browser,
            fg="#b7d6e3",
            bg="#06111f",
            selectcolor="#0a1b2c",
            activebackground="#06111f",
            activeforeground="#36f7ff",
            font=("Microsoft YaHei UI", 10),
        ).pack(side="right")

    def _build_log_area(self):
        area = tk.Frame(
            self.main,
            bg="#0a1b2c",
            highlightbackground="#17394f",
            highlightthickness=1,
        )
        area.pack(fill="both", expand=True, padx=28, pady=(0, 12))

        header = tk.Frame(area, bg="#0a1b2c")
        header.pack(fill="x", padx=16, pady=(12, 8))

        tk.Label(
            header,
            text="运行日志",
            fg="#36f7ff",
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 15, "bold"),
        ).pack(side="left")

        tk.Label(
            header,
            text="实时输出后端与前端启动信息",
            fg="#7a9cab",
            bg="#0a1b2c",
            font=("Microsoft YaHei UI", 9),
        ).pack(side="left", padx=14)

        self.clear_btn = self._button(
            header,
            "清空日志",
            self.clear_logs,
            bg="#10283a",
            fg="#9eefff",
            width=10,
            height=1,
        )
        self.clear_btn.pack(side="right")

        self.log_text = scrolledtext.ScrolledText(
            area,
            bg="#030b12",
            fg="#d9fbff",
            insertbackground="#36f7ff",
            font=("Consolas", 10),
            relief="flat",
            padx=12,
            pady=12,
            wrap="word",
        )
        self.log_text.pack(fill="both", expand=True, padx=16, pady=(0, 16))

        self.log_text.tag_config("INFO", foreground="#d9fbff")
        self.log_text.tag_config("OK", foreground="#7cffb2")
        self.log_text.tag_config("WARN", foreground="#ffd166")
        self.log_text.tag_config("ERROR", foreground="#ff6b6b")
        self.log_text.tag_config("BACKEND", foreground="#36f7ff")
        self.log_text.tag_config("FRONTEND", foreground="#7cffb2")
        self.log_text.tag_config("SYSTEM", foreground="#ffffff")

    def _build_footer(self):
        footer = tk.Frame(self.main, bg="#06111f")
        footer.pack(fill="x", padx=28, pady=(0, 14))

        tk.Label(
            footer,
            text="© 2026 智慧空气质量预测系统 | 田宇栋",
            fg="#36f7ff",
            bg="#06111f",
            font=("Microsoft YaHei UI", 10),
        ).pack(side="left")

        tk.Label(
            footer,
            text="关闭窗口前建议先点击“停止全部”",
            fg="#6ea8b5",
            bg="#06111f",
            font=("Microsoft YaHei UI", 9),
        ).pack(side="right")

    def _button(self, parent, text, command, bg, fg, width=12, height=2):
        btn = tk.Button(
            parent,
            text=text,
            command=command,
            width=width,
            height=height,
            bg=bg,
            fg=fg,
            activebackground="#123b58",
            activeforeground="#ffffff",
            bd=0,
            relief="flat",
            cursor="hand2",
            font=("Microsoft YaHei UI", 10, "bold"),
        )
        return btn

    def _draw_grid(self):
        self.bg_canvas.delete("grid")

        width = max(self.root.winfo_width(), 1180)
        height = max(self.root.winfo_height(), 760)

        grid_color = "#0b2335"

        for x in range(0, width, 46):
            self.bg_canvas.create_line(x, 0, x, height, fill=grid_color, tags="grid")

        for y in range(0, height, 46):
            self.bg_canvas.create_line(0, y, width, y, fill=grid_color, tags="grid")

        self.bg_canvas.create_line(
            0,
            92,
            width,
            92,
            fill="#0e3d52",
            width=2,
            tags="grid",
        )

        self.root.after(1200, self._draw_grid)

    # =====================================================
    # 日志与状态
    # =====================================================

    def log(self, text, tag="INFO"):
        timestamp = time.strftime("%H:%M:%S")
        self.log_queue.put((f"[{timestamp}] {text}\n", tag))

    def log_raw(self, text, tag="INFO"):
        self.log_queue.put((text, tag))

    def _poll_log_queue(self):
        try:
            while True:
                text, tag = self.log_queue.get_nowait()
                self.log_text.insert("end", text, tag)
                self.log_text.see("end")
        except queue.Empty:
            pass

        self.root.after(80, self._poll_log_queue)

    def clear_logs(self):
        self.log_text.delete("1.0", "end")

    def update_status_labels(self):
        self.backend_status_var.set(self._status_text(self.backend))
        self.frontend_status_var.set(self._status_text(self.frontend))

        self.backend_pid_var.set(str(self.backend.pid or ("外部" if self.backend.external_running else "--")))
        self.frontend_pid_var.set(str(self.frontend.pid or ("外部" if self.frontend.external_running else "--")))

        backend_running = self.backend.running
        frontend_running = self.frontend.running

        if backend_running and frontend_running:
            self.system_status_var.set("运行中")
        elif backend_running or frontend_running:
            self.system_status_var.set("部分运行")
        elif self.starting:
            self.system_status_var.set("启动中")
        elif self.stopping:
            self.system_status_var.set("停止中")
        else:
            self.system_status_var.set("待启动")

    def _status_text(self, service: ServiceProcess) -> str:
        if service.running:
            if service.external_running and not service.pid:
                return "已运行"

            return "运行中"

        if is_port_open("127.0.0.1", service.port):
            return "端口占用"

        return "未启动"

    def _refresh_status_loop(self):
        self.update_status_labels()
        self.root.after(1000, self._refresh_status_loop)


    # =====================================================
    # 数据库配置与验证
    # =====================================================

    def get_database_config(self) -> dict:
        config = {
            "DB_HOST": self.db_host_var.get().strip(),
            "DB_PORT": self.db_port_var.get().strip(),
            "DB_NAME": self.db_name_var.get().strip(),
            "DB_USER": self.db_user_var.get().strip(),
            "DB_PASSWORD": self.db_password_var.get(),
        }

        missing = [key for key in ["DB_HOST", "DB_PORT", "DB_NAME", "DB_USER"] if not config[key]]

        if missing:
            raise ValueError("数据库配置缺少必填项：" + ", ".join(missing))

        try:
            port = int(config["DB_PORT"])
        except Exception:
            raise ValueError("数据库端口必须是数字，例如 5432")

        if port <= 0 or port > 65535:
            raise ValueError("数据库端口必须在 1 到 65535 之间")

        return config

    def apply_database_env(self, env: dict) -> dict:
        config = self.get_database_config()

        for key, value in config.items():
            env[key] = str(value)

        return env

    def save_database_config(self, silent: bool = False):
        try:
            config = self.get_database_config()
            write_db_env_file(DB_ENV_PATH, config)
            self.db_status_var.set("已保存，未验证")
            self.log(f"数据库配置已保存到：{DB_ENV_PATH}", "OK")

            if not silent:
                messagebox.showinfo("保存成功", f"数据库配置已保存到：\n{DB_ENV_PATH}")

        except Exception as exc:
            self.db_status_var.set("保存失败")
            self.log(f"数据库配置保存失败：{exc}", "ERROR")

            if not silent:
                messagebox.showerror("保存失败", str(exc))

            raise

    def verify_database_async(self):
        thread = threading.Thread(target=self._verify_database_worker, daemon=True)
        thread.start()

    def _verify_database_worker(self):
        try:
            self.db_status_var.set("验证中...")
            config = self.get_database_config()
            ok, message = self.run_database_check(config)

            if ok:
                self.db_status_var.set("验证通过")
                self.log("数据库连接验证通过。", "OK")
                messagebox.showinfo("验证通过", message)
            else:
                self.db_status_var.set("验证失败")
                self.log("数据库连接验证失败：" + message, "ERROR")
                messagebox.showerror("验证失败", message)

        except Exception as exc:
            self.db_status_var.set("验证失败")
            self.log(f"数据库配置错误：{exc}", "ERROR")
            messagebox.showerror("数据库配置错误", str(exc))

    def run_database_check(self, config: dict):
        python_code = '''
import os
import sys

try:
    import psycopg2
except Exception as exc:
    print("无法导入 psycopg2：" + str(exc))
    sys.exit(2)

try:
    conn = psycopg2.connect(
        host=os.environ.get("DB_HOST"),
        port=int(os.environ.get("DB_PORT", "5432")),
        dbname=os.environ.get("DB_NAME"),
        user=os.environ.get("DB_USER"),
        password=os.environ.get("DB_PASSWORD", ""),
        connect_timeout=5,
    )
    cur = conn.cursor()
    cur.execute("SELECT 1")
    cur.fetchone()
    cur.close()
    conn.close()
    print("数据库连接成功。")
except Exception as exc:
    print(str(exc))
    sys.exit(1)
'''

        try:
            python_cmd = get_python_command()
        except Exception as exc:
            return False, str(exc)

        env = os.environ.copy()
        env.update(config)
        env["PYTHONIOENCODING"] = "utf-8"

        kwargs = {}

        if is_windows():
            kwargs["creationflags"] = subprocess.CREATE_NO_WINDOW

        try:
            result = subprocess.run(
                [python_cmd, "-c", python_code],
                cwd=str(PROJECT_ROOT),
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=12,
                check=False,
                **kwargs,
            )
        except subprocess.TimeoutExpired:
            return False, "连接数据库超时，请检查主机、端口、防火墙和 PostgreSQL 服务状态。"
        except Exception as exc:
            return False, str(exc)

        output = (result.stdout or "").strip()

        if result.returncode == 0:
            return True, output or "数据库连接成功。"

        return False, output or f"数据库连接失败，退出码：{result.returncode}"

    # =====================================================
    # 环境检查
    # =====================================================

    def check_environment(self):
        self.log("开始环境检查...", "SYSTEM")

        checks = []

        checks.append(("项目根目录", PROJECT_ROOT.exists(), str(PROJECT_ROOT)))
        checks.append(("backend 目录", (PROJECT_ROOT / "backend").exists(), str(PROJECT_ROOT / "backend")))
        checks.append(("frontend 目录", (PROJECT_ROOT / "frontend").exists(), str(PROJECT_ROOT / "frontend")))
        checks.append(("backend/app.py", (PROJECT_ROOT / "backend" / "app.py").exists(), str(PROJECT_ROOT / "backend" / "app.py")))
        checks.append(("frontend/package.json", (PROJECT_ROOT / "frontend" / "package.json").exists(), str(PROJECT_ROOT / "frontend" / "package.json")))
        checks.append(("frontend/node_modules", (PROJECT_ROOT / "frontend" / "node_modules").exists(), str(PROJECT_ROOT / "frontend" / "node_modules")))
        checks.append(("数据库配置文件 .env", DB_ENV_PATH.exists(), str(DB_ENV_PATH) if DB_ENV_PATH.exists() else "未保存，可在启动器中填写后保存"))

        try:
            python_cmd = get_python_command()
            checks.append(("Python", True, python_cmd))
        except Exception as exc:
            checks.append(("Python", False, str(exc)))

        try:
            npm_cmd = get_npm_command()
            checks.append(("npm", True, npm_cmd))
        except Exception as exc:
            checks.append(("npm", False, str(exc)))

        checks.append((f"后端端口 {BACKEND_PORT}", not is_port_open("127.0.0.1", BACKEND_PORT), "空闲" if not is_port_open("127.0.0.1", BACKEND_PORT) else "已占用"))
        checks.append((f"前端端口 {FRONTEND_PORT}", not is_port_open("127.0.0.1", FRONTEND_PORT), "空闲" if not is_port_open("127.0.0.1", FRONTEND_PORT) else "已占用"))

        ok_count = 0

        for name, ok, detail in checks:
            if ok:
                ok_count += 1
                self.log(f"√ {name}：{detail}", "OK")
            else:
                self.log(f"× {name}：{detail}", "ERROR")

        self.log(f"环境检查完成：{ok_count}/{len(checks)} 项通过", "SYSTEM")

    # =====================================================
    # 启动逻辑
    # =====================================================

    def start_all(self):
        if self.starting:
            return

        thread = threading.Thread(target=self._start_all_worker, daemon=True)
        thread.start()

    def _start_all_worker(self):
        self.starting = True
        self.update_status_labels()

        self.log("=" * 70, "SYSTEM")
        self.log("开始启动 PM2.5 监控预警平台...", "SYSTEM")
        self.log(f"项目根目录：{PROJECT_ROOT}", "SYSTEM")
        self.log("=" * 70, "SYSTEM")

        try:
            self.log("正在保存并验证数据库配置...", "SYSTEM")
            self.save_database_config(silent=True)

            db_ok, db_message = self.run_database_check(self.get_database_config())

            if not db_ok:
                self.db_status_var.set("验证失败")
                raise RuntimeError("数据库连接验证失败：" + db_message)

            self.db_status_var.set("验证通过")
            self.log("数据库连接验证通过，继续启动后端。", "OK")

            self._start_backend()
            self._start_frontend()

            if self.auto_open_browser.get():
                self.log("准备打开浏览器...", "SYSTEM")
                time.sleep(1.2)
                self.open_frontend()

            self.log("启动流程执行完成。", "OK")

        except Exception as exc:
            self.log(f"启动失败：{exc}", "ERROR")
            messagebox.showerror("启动失败", str(exc))

        finally:
            self.starting = False
            self.update_status_labels()

    def _start_backend(self):
        if is_port_open("127.0.0.1", BACKEND_PORT):
            self.backend.external_running = True
            self.log(f"后端端口 {BACKEND_PORT} 已被占用，视为后端已运行：{BACKEND_URL}", "WARN")
            return

        python_cmd = get_python_command()

        env = os.environ.copy()
        env = self.apply_database_env(env)
        env["PYTHONIOENCODING"] = "utf-8"
        env["PYTHONUNBUFFERED"] = "1"

        cmd = [
            python_cmd,
            "-m",
            "uvicorn",
            "backend.app:app",
            "--reload",
            "--port",
            str(BACKEND_PORT),
        ]

        self.log("正在启动后端 FastAPI...", "BACKEND")
        self.log("后端命令：" + " ".join(cmd), "BACKEND")

        creation_flags = 0

        if is_windows():
            creation_flags = subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.CREATE_NO_WINDOW

        process = subprocess.Popen(
            cmd,
            cwd=str(BACKEND_DIR),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
            creationflags=creation_flags,
        )

        self.backend.process = process
        self.backend.external_running = False

        threading.Thread(
            target=self._stream_output,
            args=(process, "后端", "BACKEND"),
            daemon=True,
        ).start()

        self.log("等待后端端口启动...", "BACKEND")

        if wait_for_port("127.0.0.1", BACKEND_PORT, timeout=40):
            self.log(f"后端启动成功：{BACKEND_URL}", "OK")
        else:
            self.log("后端启动等待超时，请查看日志。", "ERROR")

    def _start_frontend(self):
        if is_port_open("127.0.0.1", FRONTEND_PORT):
            self.frontend.external_running = True
            self.log(f"前端端口 {FRONTEND_PORT} 已被占用，视为前端已运行：{FRONTEND_URL}", "WARN")
            return

        package_json = FRONTEND_DIR / "package.json"

        if not package_json.exists():
            raise RuntimeError(f"未找到 frontend/package.json：{package_json}")

        node_modules = FRONTEND_DIR / "node_modules"

        if not node_modules.exists():
            raise RuntimeError(
                "未找到 frontend/node_modules。\n\n"
                "请先在 frontend 目录执行：\n"
                "npm install"
            )

        npm_cmd = get_npm_command()

        cmd = [
            npm_cmd,
            "run",
            "dev",
            "--",
            "--host",
            "0.0.0.0",
        ]

        self.log("正在启动前端 Vite...", "FRONTEND")
        self.log("前端命令：" + " ".join(cmd), "FRONTEND")

        creation_flags = 0

        if is_windows():
            creation_flags = subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.CREATE_NO_WINDOW

        process = subprocess.Popen(
            cmd,
            cwd=str(FRONTEND_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
            creationflags=creation_flags,
        )

        self.frontend.process = process
        self.frontend.external_running = False

        threading.Thread(
            target=self._stream_output,
            args=(process, "前端", "FRONTEND"),
            daemon=True,
        ).start()

        self.log("等待前端端口启动...", "FRONTEND")

        if wait_for_port("127.0.0.1", FRONTEND_PORT, timeout=40):
            self.log(f"前端启动成功：{FRONTEND_URL}", "OK")
        else:
            self.log("前端启动等待超时，请查看日志。", "ERROR")

    def _stream_output(self, process, prefix, tag):
        if not process.stdout:
            return

        for line in iter(process.stdout.readline, ""):
            if not line:
                break

            self.log_raw(f"[{prefix}] {line}", tag)

        code = process.poll()

        if code is not None:
            self.log(f"{prefix}进程已退出，退出码：{code}", "WARN")

    # =====================================================
    # 停止逻辑
    # =====================================================

    def stop_all(self):
        if self.stopping:
            return

        thread = threading.Thread(target=self._stop_all_worker, daemon=True)
        thread.start()

    def _stop_all_worker(self):
        self.stopping = True
        self.update_status_labels()

        self.log("正在停止所有服务...", "SYSTEM")

        self._stop_service(self.frontend, "前端")
        self._stop_service(self.backend, "后端")

        self.log("停止流程执行完成。", "OK")

        self.stopping = False
        self.update_status_labels()

    def _stop_service(self, service: ServiceProcess, label: str):
        if service.process and service.process.poll() is None:
            pid = service.process.pid
            self.log(f"正在停止{label}进程 PID={pid}", "SYSTEM")

            try:
                if is_windows():
                    taskkill_pid(pid)
                else:
                    service.process.terminate()
                    time.sleep(1)

                    if service.process.poll() is None:
                        service.process.kill()

                self.log(f"{label}进程已停止。", "OK")

            except Exception as exc:
                self.log(f"{label}停止失败：{exc}", "ERROR")

        elif service.external_running:
            self.log(f"{label}是外部已运行服务，启动器不会强制停止。", "WARN")

        else:
            self.log(f"{label}未启动，无需停止。", "INFO")

        service.process = None
        service.external_running = False

    def restart_all(self):
        def worker():
            self._stop_all_worker()
            time.sleep(1.5)
            self._start_all_worker()

        threading.Thread(target=worker, daemon=True).start()

    # =====================================================
    # 其他
    # =====================================================

    def open_frontend(self):
        if is_port_open("127.0.0.1", FRONTEND_PORT):
            webbrowser.open(FRONTEND_URL)
            self.log(f"已打开系统页面：{FRONTEND_URL}", "OK")
        else:
            self.log("前端服务尚未启动，无法打开页面。", "WARN")
            messagebox.showwarning("前端未启动", "前端服务尚未启动，无法打开页面。")

    def on_close(self):
        backend_running = self.backend.running
        frontend_running = self.frontend.running

        if backend_running or frontend_running:
            ok = messagebox.askyesno(
                "确认退出",
                "检测到前端或后端服务仍在运行。\n\n"
                "是否停止服务并退出启动器？"
            )

            if ok:
                self._stop_all_worker()
                self.root.destroy()
            else:
                self.root.destroy()
        else:
            self.root.destroy()


def main():
    root = tk.Tk()

    try:
        app = TechLauncher(root)
        app.log("启动器已就绪。", "OK")
        app.log("点击“环境检查”可检查 Python、npm、node_modules 和端口状态。", "SYSTEM")
        app.log("请先填写数据库配置并点击“验证数据库”，再点击“启动全部”。", "SYSTEM")
        app.log("点击“启动全部”会自动保存并验证数据库配置，然后启动后端和前端。", "SYSTEM")

        root.mainloop()

    except Exception as exc:
        messagebox.showerror("启动器初始化失败", str(exc))
        raise


if __name__ == "__main__":
    main()